[package]
name = "example_project"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
mpi_test_macros = { path = "../mpi_test_macros" }
mpi_test_runner = { path = "../mpi_test_runner" }
mpi = "0.8"
rstest = "0.26.1"
